### ISSUE TITLE
bind the data after a ajax call

### ISSUE THREAD

**Issue by c625473164** [SevenOutman/vue-aplayer#1]
is there any way to send music list data to the :music prop after an ajax call

**Comment by xuzili1993** [comment]
老表 能来个中文文档吗

**Comment by SevenOutman** [comment]
@c625473164 APlayer doesn't have song list mutation apis yet, so vue-aplayer is not able to modify the song list after construction as well. You may try construct vue-aplayer component after the ajax call.

**Comment by ecitlm** [comment]
Excuse me,When the father component get an ajax data,the data can't set to the  VueAplayer compoent ,It's also the old Initially data ,so can't play new data ,Excuse me
```         
get: function () {
                var id = this.$route.query.id;
                axios.get(musicApi + id + '&ids=[' + id + ']').then(function (res) {
                    this.list = res.data.songs[0];

                    this.music = {
                        title: this.list.name,
                        author: this.list.artists[0].name,
                        url: this.list.mp3Url,
                        pic: this.list.album.picUrl,
                        lrc: '[00:00.00]lrc here\n[00:01.00]aplayer'
                    };
                    Indicator.close();

                }.bind(this)).catch(function (error) {
                    console.log(error)
                })
            }

**Comment by SevenOutman** [comment]
@ecitlm APlayer doesn't provide an api to mutate the music list after it's been created.

**Comment by c625473164** [comment]
I have solved my problem by using <v-if> to render the component after an ajax.

**Comment by ecitlm** [comment]
@c625473164  能否提供一下代码片段呢，provide the code can you ?
