### ISSUE TITLE
Is it possible to retrieve source url only when user starts to play track?

### ISSUE THREAD

**Issue by DTX-92** [SevenOutman/vue-aplayer#103]
I have array of audios:
```
[
  {id: 1, 'Title1', 'Artist1'},
  {id: 2, 'Title2', 'Artist2'},
  {id: 3, 'Title3', 'Artist3'},
]
```
And i can only get temporary url by passing id to server.
So can i use this plugin for these purposes?

**Comment by SevenOutman** [comment]
@DTX-92 Render `<aplayer>` after you've already got the urls, using `v-if` or any other approach.
