### ISSUE TITLE
播放器 播放中，动态改变播放器外层样式变量。导致播放器暂停？

### ISSUE THREAD

**Issue by qiter** [SevenOutman/vue-aplayer#107]
播放器 播放中，动态改变播放器外层样式变量。导致播放器暂停？
我做了一个把播放器，滚动页面放置顶部的功能。只是动态改变了css。做到div fixed。。没有操作播放器代码。也导致了播放器暂停

**Comment by SevenOutman** [comment]
@qiter 修改父组件的属性可能导致子组件被重新渲染。
