### ISSUE TITLE
vue-aplayer使用js动态加载组件不显示的问题

### ISSUE THREAD

**Issue by Sweetjqq** [SevenOutman/vue-aplayer#110]

**Comment by Sweetjqq** [comment]
你好，我使用js动态把vue-aplayer插入到div中，vue-aplayer不显示

**Comment by SevenOutman** [comment]
@Sweetjqq 请展示相关代码、截图等信息，描述预期结果和实际结果。

**Comment by Sweetjqq** [comment]
let src = OneAudio.getAttribute("src");
                  let message = {
                    src: src,
                  };
                  message = JSON.stringify(message);
                  let link = '<Aplayer :music=' + "'" + message + "'" + '> </Aplayer>';
                  console.log(link, "***********link**********");
                  OneAudio.parentNode.innerHTML=link;
但是页面中不显示aplayer的效果

**Comment by Sweetjqq** [comment]
我如果把link的代码复制出来，放在页面中就能显示。但是动态插入到页面中就是不行

**Comment by SevenOutman** [comment]
@Sweetjqq 建议你先好好了解一下 Vue 的用法，这样用肯定是不行的。
