### ISSUE TITLE
想问一下这个播放器能不能自适应屏幕的。

### ISSUE THREAD

**Issue by xintao-taotao** [SevenOutman/vue-aplayer#111]
我的网站需要做自适应，不知道这个播放器能不能满足我的要求，我怕到时候到了手机上这个播放器变形了那就惨了。

**Comment by DIYgod** [comment]
@xintao-taotao 不能，别用

**Comment by SevenOutman** [comment]
@xintao-taotao 没有做自适应。手机上的样式调整参考 https://github.com/SevenOutman/vue-aplayer/issues/79
