### ISSUE TITLE
动态更换:music对象后播放的还是最开始默认的音频

### ISSUE THREAD

**Issue by jgsrty** [SevenOutman/vue-aplayer#113]
自己做的播放列表，点击播放列表 更换：music的参数，再点击播放还是之前的音频 这是咋回事呢

**Comment by SevenOutman** [comment]
@jgsrty 文字描述不如贴点代码来的清楚？

**Comment by ycfang** [comment]
<a-player  ref="videoPlayer"
                     :music="playerOptions"
                     :list="playList"
                     autoplay>
 </a-player>
playerOptions: {
          title:'',
          artist:'',
          src:require('../assets/banfenghe.mp3'),
          pic:require('../static/img/plant1/4a36acaf2edda3ccd08041d001e93901203f92de.jpg')
      },

点击的时候，切换music对象后播放的还是最开始默认的音频
this.playerOptions.src=require('../assets/jinzhiwen.mp3')

**Comment by SevenOutman** [comment]
@ycfang 这没有更换 `music` 对象吧，只是给原来的 `music` 的 `src` 字段赋了个值。

**Comment by jgsrty** [comment]
嗯 只是更改了src，原生audio改src切换播放源。。。自己手写了个简陋版的。。

**Comment by jgsrty** [comment]
嗯 谢谢~

**Comment by ycfang** [comment]
@SevenOutman OK,明白了。我直接替换对象就可以了，还有就是autoplay如果是动态绑定以后
:autoplay="isPlay"，
isPlay:false,
this.isPlay=true
切换音频的时候不会自动播放是怎么回事
