### ISSUE TITLE
自动播放动态绑定切换无效

### ISSUE THREAD

**Issue by ycfang** [SevenOutman/vue-aplayer#115]
<a-player  ref="videoPlayer"
                     :music="playerOptions"
                     :autoplay="isPlay">
 </a-player>
isPlay:false,
this.playerOptions={title:'半枫荷',src:require('../assets/jinzhiwen.mp3'),pic:require('../assets/img/plant1/4a36acaf2edda3ccd08041d001e93901203f92de.jpg'),artist:''}
this.isPlay=true
动态切换以后，音频变了，但是无法自动播放

**Comment by SevenOutman** [comment]
@ycfang `autoplay` 只接收最开始的值的，后面改成 `true` 是没有效果的
https://github.com/SevenOutman/vue-aplayer/blob/develop/docs/README.md#audio-attributes-as-props

**Comment by ycfang** [comment]
那如果要实现我的这种功能怎么办，我需要切换的时候就要自动播放

**Comment by SevenOutman** [comment]
@ycfang 在切换歌曲后调用 `aplayer.thenPlay()`

**Comment by ycfang** [comment]
需要设置ref？this.$refs.aplayer.thenPlay()

**Comment by SevenOutman** [comment]
@ycfang 对

**Comment by ycfang** [comment]
感谢

**Comment by chenendian** [comment]
为何我在mounted里面调用this.$refs.aplayer.thenPlay()  还是没有自动播放

**Comment by walijoy** [comment]
"TypeError: this.$refs.aplayer.thenPlay is not a function"
