### ISSUE TITLE
無法顯示圖片

### ISSUE THREAD

**Issue by maple3142** [SevenOutman/vue-aplayer#116]
如題
右邊是傳給 `music` 的內容，那個 `pic` 的路徑也確實存在
但為什麼圖片卻無法顯示? 音樂倒是可以正常撥放
![image](https://user-images.githubusercontent.com/9370547/46093367-c2877c80-c1e9-11e8-9895-9665f81665d4.png)

**Comment by SevenOutman** [comment]
@maple3142 你的控制台显示有2处报错，也许与它们有关

**Comment by maple3142** [comment]
那個只是 warning 而已，也不會有嚴重影響
而 aplayer 的 `background-image` 不知為何是被設成預設的圖片
![image](https://user-images.githubusercontent.com/9370547/46144209-d46f2b00-c28e-11e8-80c6-179de50a544d.png)

**Comment by SevenOutman** [comment]
@maple3142 是只有 `pic` 是本地路径的时候会这样？还是使用 URL 也会这样？

**Comment by SevenOutman** [comment]
@maple3142 实际场景中通常这些资源大多是托管在服务器上的，用的是 URL，应该问题不大

**Comment by maple3142** [comment]
我最後用了 `pic: JSON.stringify('file://' + localImageUrl)` 的方法解決了，感謝
