### ISSUE TITLE
这个插件如何添加监听事件  需要使用js 获取dom然后再添加是吗？ 

### ISSUE THREAD

**Issue by chenendian** [SevenOutman/vue-aplayer#120]

**Comment by SevenOutman** [comment]
@chenendian 要监听什么事件？

**Comment by chenendian** [comment]
比如暂停、播放的时候触发一个回掉    我能完成一些页面的其它操作   我现在的做法是使用原生js找到这个audio标签  然后给这个标签添加原生的事件

**Comment by SevenOutman** [comment]
@chenendian 参考这里 https://github.com/SevenOutman/vue-aplayer/blob/develop/docs/README.zh-CN.md#%E4%BA%8B%E4%BB%B6 

```vue
<aplayer @pause="onPause" />
```

**Comment by chenendian** [comment]
好的 谢啦  我点进去看到那个mdn的例子以为只能通过原生的绑定呢  谢啦
