### ISSUE TITLE
Error in callback for watcher "music": "TypeError: Cannot read property 'pic' of undefined"  found in  ---> <APlayer>

### ISSUE THREAD

**Issue by ExcuseM** [SevenOutman/vue-aplayer#15]
Error in callback for watcher "music": "TypeError: Cannot read property 'pic' of undefined"
可以正常播放，但进入页面就报错

**Comment by 50l3r** [comment]
+1

Property exist in my config:

![image](https://i.gyazo.com/4c43e87933b9d2f214bc3a26497064e4.png)

**Comment by ericdrobinson** [comment]
The root of this issue appears to be in APlayer itself. We saw the same thing described here while attempting to build a quick example of a different bug. Take a look at the browser's JavaScript console after you press the "Swap" button in [this example](https://jsfiddle.net/fqq058v8/2/).

I would _suggest_ looking to fix the issue in the APlayer repo, but a possible workaround may be to change [this line](https://github.com/SevenOutman/vue-aplayer/blob/master/src/vue-aplayer.vue#L66) to:
```js
this.control.option.music[0] = music;
```

**Comment by SevenOutman** [comment]
@ExcuseM @50l3r @ericdrobinson Please try out recent v1.x version.
