### ISSUE TITLE
折叠列表图标怎么配置才显示出来？文档上没有写。

### ISSUE THREAD

**Issue by 1015770492** [SevenOutman/vue-aplayer#178]
![~ NA}{WC$)J~HLR7N)NJ5W0](https://user-images.githubusercontent.com/43501801/66712693-fa506a80-edd2-11e9-8c29-9e978ae1fc09.png)
如图代码
![1MHQG18SK}MCHJK143HHDHM](https://user-images.githubusercontent.com/43501801/66712709-56b38a00-edd3-11e9-8705-3e427ff194e2.png)

显示效果
![}B6S5%MXU@5FIYBB7EJ5%5K](https://user-images.githubusercontent.com/43501801/66712706-4b605e80-edd3-11e9-9c64-63f98a745478.png)

**Comment by SevenOutman** [comment]
@1015770492 根据文档，`list` 是个数组

**Comment by 1015770492** [comment]
收到，解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Doma"<notifications@github.com&gt;; 
发送时间: 2019年10月13日(星期天) 下午5:47
收件人: "SevenOutman/vue-aplayer"<vue-aplayer@noreply.github.com&gt;; 
抄送: "(11I10I24) 活 动 中 心"<1015770492@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [SevenOutman/vue-aplayer] 折叠列表图标怎么配置才显示出来？文档上没有写。 (#178)




@1015770492 根据文档，list 是个数组
