### ISSUE TITLE
怎么配置自适应主题？

### ISSUE THREAD

**Issue by AbelEthan** [SevenOutman/vue-aplayer#198]
1. 现在colorthief可以使用npm安装了，我也安装了。
2. 我的主题设置是这样的：![image](https://user-images.githubusercontent.com/30233209/79540490-d724b180-80ba-11ea-8de6-c607c28bc9ba.png)

**Comment by AbelEthan** [comment]
我测试半天使用npm安装的都无效，最后放弃了就在index.html引入js才成功
![image](https://user-images.githubusercontent.com/30233209/79549408-85cfee80-80c9-11ea-86f2-ca2c6d68f59b.png)

 这是效果图
![image](https://user-images.githubusercontent.com/30233209/79549444-91231a00-80c9-11ea-97f6-3156bd362c88.png)

**Comment by SevenOutman** [comment]
目前没有适配 npm 安装的 colorthief
