### ISSUE TITLE
怎么添加移动进度条进行快进和后退

### ISSUE THREAD

**Issue by duancong** [SevenOutman/vue-aplayer#22]
现在移动进度条都是重新开始

**Comment by SevenOutman** [comment]
@duancong 未能重现。我在 [vue-aplayer.js.org](https://vue-aplayer.js.org/) 上的 demo 都是可以拖动进度条进行定位的，你也试下。如果不行的话，提供下你使用的浏览器版本和操作系统版本。

**Comment by SevenOutman** [comment]
Resolved during email contact. Closed due to inactivity.

**Comment by gjycdd** [comment]
@SevenOutman 我复现了这个问题，有可能和定位有关系
示例代码如下：
```
<div class="mediaAudio position-center" v-show="type === 'audio' && isStart">
        <aplayer
          ref="mediaAudio"
          preload="preload"
          :music="dynamic"
        />
</div>
```
```
.position-center {
     position: absolute;
     left: 50%;
     top: 50%;
     transform: translate(-50%, -50%);
}
```
当我移除类名position-center时，拖动正常，添加则拖动从头开始。

**Comment by SevenOutman** [comment]
@gjycdd 这是 `transform` 导致的。没有针对这一用例进行修复的计划，你可以使用其他方案代替 `transform` 进行定位，比如使用 `margin` 等。

**Comment by gjycdd** [comment]
@SevenOutman ok，liaokai

**Comment by jsbtn** [comment]
好像并不是您说得这样

**Comment by jsbtn** [comment]
我在外层只添加了个盒子  然后播放器会自动添加一个 transform: translate(0, 0)的内联样式。不管咋弄都无法拖动

**Comment by jsbtn** [comment]
后来查证是音频格式可能有问题 。 .ogg 格式在火狐和谷歌都能拖动。
