### ISSUE TITLE
切换路由,改变变量导致播放停止重置,找到解决办法了

### ISSUE THREAD

**Issue by lxhlxh520** [SevenOutman/vue-aplayer#247]
<div class="aplayercontainer" v-once>
      <aplayer
      ref="aplayer"
      mini
      float
      repeat="repeat-all"
      :music="{
        src: musicsrc,
        pic: musicpic,
      }"
    />
    </div>
[v-once](https://v2.vuejs.org/v2/guide/components-edge-cases.html#Cheap-Static-Components-with-v-once)

**Comment by SevenOutman** [comment]
Hi @lxhlxh520 ，感谢反馈。看上去这不是一个问题，我将会将此 Issue 转换为 Discussion
