### ISSUE TITLE
listFolded option?

### ISSUE THREAD

**Issue by shilik** [SevenOutman/vue-aplayer#27]
Do you plan to implement the listFolded option as the original aplayer?
I have added listFolded=true to vue-aplyer, but it didn't work as expected.

**Comment by SevenOutman** [comment]
@shilik Yes. It's a useful option and I did plan to add it. I'm currently looking for a good balance between fewer redundant props and a less confusing naming. Hopefully it will be add in next patch release.

For now, if you want to play a list of songs with playlist not showing, you can listen to `ended` event and change `music` prop passed to Vue-APlayer.

**Comment by SevenOutman** [comment]
@shilik Added in [`v1.4.1`](https://github.com/SevenOutman/vue-aplayer/releases/tag/1.4.1)

**Comment by shilik** [comment]
Thanks so much for your great efforts and patch! Great Job!
