### ISSUE TITLE
 shrink the songlist automatically?

### ISSUE THREAD

**Issue by shilik** [SevenOutman/vue-aplayer#29]
I have managed to make the listFolded prop work at the initial phase of loading site.
I just wonder if there any way to trigger the toggle button event, when I click any item in the song list?
I tried to include this.listFolded = !this.listFolded in the @play event, and it turned out that this property can be altered, but the opened songlist remains unchanged. any idea?

**Comment by SevenOutman** [comment]
@shilik I've put some external control capability into `v1.4.0`, but currently toggling playlist is not one of them.
I'm considering adding more playlist interactions in next minor update (as v1.5.0), along with some custom events that you can listen to.

For now, if you want to toggle the playlist, you can get the ref of your player and mutate its `showList` property.

```
const player = this.$refs.aplayer
player.showList = !player.showList
```

**Comment by shilik** [comment]
Thanks again for the quick replay. I have made the project to function the
way I want based on your suggestion.
You are awesome!  \o/


2018-03-27 19:33 GMT+08:00 Doma <notifications@github.com>:
