### ISSUE TITLE
Log info emitting version badge information

### ISSUE THREAD

**Issue by sabby62** [SevenOutman/vue-aplayer#31]
Not sure, if this is intended or just a debugging left over.  
Line# 67 & 68 in vue-aplayer.vue

**Comment by SevenOutman** [comment]
@sabby62 Intended.

**Comment by tanghui28** [comment]
how to get the seconds of the  song

**Comment by SevenOutman** [comment]
@tanghui28 Either `player.audio.currentTime` or `player.playStat.playedTime` returns current playing seconds of the soundtrack, where `player` is the component instance reference.
