### ISSUE TITLE
你好,请问怎么控制播放停止?

### ISSUE THREAD

**Issue by anyudi** [SevenOutman/vue-aplayer#32]
首先感谢作者!
我在使用的时候,把播放器 放在了弹出层中,我需要在弹出层关闭的时候,使播放器停止播放,但我在API中没有看到控制停止的方法.请问有关闭的方法吗?
感激~~~~~~~~

**Comment by anyudi** [comment]
已解决~

**Comment by SevenOutman** [comment]
@anyudi 解决了就好。
以供参考，可以使用组件实例上的 `.pause()` 方法：
```
this.$refs.player.pause()
```
