### ISSUE TITLE
vue-aplayer.min.js in node_modules is huge (over 2M)

### ISSUE THREAD

**Issue by z08w12** [SevenOutman/vue-aplayer#33]
安装后vue-aplayer.min.js体积很大，达到了2M多，请问这正常吗？我看前面版本的只有200多k

**Comment by SevenOutman** [comment]
@z08w12 请问你是在哪里看到的 2M 多呢？我访问 https://unpkg.com/vue-aplayer@1.4.2/dist/vue-aplayer.min.js 在检查器里看到体积是 659K。

**Comment by z08w12** [comment]
@SevenOutman 我是npm install后在包里的dist/vue-aplayer.min.js看的

**Comment by SevenOutman** [comment]
@z08w12 的确有这个问题，会尽快解决。

**Comment by z08w12** [comment]
@SevenOutman 谢谢

**Comment by SevenOutman** [comment]
@z08w12 已在 `v1.4.3` 中修复了这个问题 (53b4a1902342e9526433ce7c165d6150518540a9)，目前体积是 50+K (gzip 16K)
