### ISSUE TITLE
document is not defined In NUXT JS

### ISSUE THREAD

**Issue by Shadomax** [SevenOutman/vue-aplayer#35]
When i import the plugin in a Nuxt.js page i get a document not defined. Can these plugin work in SSR for example Nuxt.js

**Comment by Shadomax** [comment]
I solved my own problem. created a new plugin under the nuxt plugins directory and added the plugin to the nuxt.config.js file and disabled server-side-rendering option
`{ src: '~plugins/vue-aplayer', ssr: false },` 
everything is working fine now

**Comment by SevenOutman** [comment]
@Shadomax Glad you have solved it! Vue-APlayer has not been tested out with SSR, but I believe `audio` element does not work well with SSR.

**Comment by smilingpeanut** [comment]
I tried this same method and the `document` error is still occurring. Any thoughts @SevenOutman?

**Comment by SevenOutman** [comment]
@Shadomax As explained before, Vue-APlayer probably doesn't work with SSR.

**Comment by smilingpeanut** [comment]
Right, I totally get that. But with SSR off as in the previous comment, the bug is still occurring.

**Comment by SevenOutman** [comment]
@smilingpeanut Well I'll look into it.
