### ISSUE TITLE
请问如何安装没有hls.js的版本

### ISSUE THREAD

**Issue by lixajh** [SevenOutman/vue-aplayer#36]
因为hls.js体积很大，请问是否支持安装没有hls.js的版本？

**Comment by SevenOutman** [comment]
@lixajh 请说的具体一点，看不懂你想问什么

**Comment by lixajh** [comment]
不好意思，不小心按到回车就发出去了。手动允悲。

**Comment by SevenOutman** [comment]
@lixajh Vue-APlayer 并不会自动安装 hls.js。如果你需要支持 m3u8，你需要手动安装 hls.js。你可以在[文档](https://github.com/SevenOutman/vue-aplayer/blob/develop/docs/README.zh-CN.md#%E6%94%AF%E6%8C%81-hls)中了解这一点。

如果这解决了你的问题，你随时可以关闭这个 issue。

**Comment by lixajh** [comment]
我是用npm安装Vue-Aplayer，之前没有安装过hls.js。然而打包项目后webpack report显示确实有hls.js。我尝试了uninstall hls.js，没有作用。

**Comment by SevenOutman** [comment]
@lixajh 请问你安装的 Vue-APlayer 是什么版本？

**Comment by lixajh** [comment]
"vue-aplayer": "^1.5.0",

**Comment by SevenOutman** [comment]
@lixajh 看起来的确是这样。

你可以使用 `--no-optional` 标记来避免安装 optional dependencies。
```shell
npm install --save vue-aplayer --no-optional
```

**Comment by SevenOutman** [comment]
@lixajh 在 `vue-aplayer@1.5.1` 中，`hls.js` 从 `optionalDependencies` 中被移除。
