### ISSUE TITLE
Suggestion: Prop to display larger icons

### ISSUE THREAD

**Issue by Sobient** [SevenOutman/vue-aplayer#37]
First off, thanks for a nice player! However, the icons are by  default very small and hard to hit. While it is possible to CSS your way to bigger buttons, it would've been nice if there was a prop for the component to resize all parts of the player (including the fonts) to a larger or smaller version and add proportional margins as well.

## Original sizing, which is (too) small
![bilde](https://user-images.githubusercontent.com/706874/39642150-fca1f480-4fd0-11e8-9e02-410de96d7e5d.png)

## Support for other sizes:
Add prop for size. Allow for various sizes, for example: `sm`,`md` (default) ,`lg`,`xl`
```
<aplayer 
  autoplay
  size="lg"
  :music="{
    title: 'secret base~君がくれたもの~',
    artist: 'Silent Siren',
    src: 'https://moeplayer.b0.upaiyun.com/aplayer/secretbase.mp3',
    pic: 'https://moeplayer.b0.upaiyun.com/aplayer/secretbase.jpg'
  }"
/>
```

### Result
![bilde](https://user-images.githubusercontent.com/706874/39642928-6d634e74-4fd3-11e8-8be7-5d3fa868eb31.png)

Side note: Some markup and CSS used in the player are dubious at best. Would suggest using flex-box and a skeleton CSS-grid instead.

**Comment by SevenOutman** [comment]
@Sobient 
> Add prop for size. Allow for various sizes, for example: sm,md (default) ,lg,xl

Good point. It's important to make buttons easier to hit, but I also care about how this player looks. So I will solve this issue, but maybe with some other solutions.

> Side note: Some markup and CSS used in the player are dubious at best. Would suggest using flex-box and a skeleton CSS-grid instead.

Can you be more specific about what you describe?

**Comment by SevenOutman** [comment]
@Sobient After several attempts, I decided not to implement this as a built-in feature. You can apply your custom styles for larger buttons.
