### ISSUE TITLE
vuex 存储 歌曲参数问题

### ISSUE THREAD

**Issue by OneKissAndOneShot** [SevenOutman/vue-aplayer#38]
'<'+'aplayer autoplay v-if="show" :music="this.$store.state.music"></aplayer>'
首先感谢作者，我在使用vuex存储 歌曲参数的时候 点击不同歌曲this.$store.state.music 里的数据已经刷新 但是页面上播放器播放的歌曲没一块更新 需要点击暂停之后在播放才刷新播放歌曲 这个是BUG么 还是我代码问题

没用VUEX 的时候直接 请求数据 更改 没问题 一用vuex就出现这个问题

**Comment by SevenOutman** [comment]
@OneKissAndOneShot 看起来是 Vue 的使用问题。为对象添加字段时，应使用 Vue.set 方法而不是直接赋值。https://cn.vuejs.org/v2/api/#Vue-set

**Comment by OneKissAndOneShot** [comment]
多谢大佬，问题已经解决 用Vue.set解决的 vuex也不是很了解 还需要多学习 抱拳了
