### ISSUE TITLE
[Vue warn]: Invalid prop: custom validator check failed for prop "music".

### ISSUE THREAD

**Issue by Robin-zero** [SevenOutman/vue-aplayer#39]
I have a component structure nested three-levels deep, but some mistakes occured, please help me find the reason at your convenience, I will be deeply grateful!!

**level1: ResourcesLibrary.vue**
```vue
<item-res-audio :file="item.content"></item-res-audio>
```

**level2: ItemResAudio.vue**
```vue
<template>
    <div class="wrap">
        <the-audio :music="music"></the-audio>
    </div>
</template>

<script type="text/ecmascript-6">
  /* eslint-disable semi */
  import TheAudio from '../item/TheAudio';
  export default {
    data() {
      return {
        music: {
          title: 'Untitled',
          src: '',
          pic: require('../../assets/images/audio.jpg'),
          theme: 'teal'
        }
      };
    },
    props: {
      file: {
        type: String,
        default: () => {
          return '';
        }
      }
    },
    mounted() {
      this.music.src = this.file;
      this.music.title = this.file.split('/')[3].split('.')[0];
    },
    beforeDestroy() {
    },
    computed: {},
    methods: {

    },
    components: {
      TheAudio
    }
  };
</script>
```

**level3: TheAudio.vue**
```vue
<template>
    <div class="wrap">
        <aplayer :music="music" />
    </div>
</template>

<script type="text/ecmascript-6">
  /* eslint-disable semi */
  import Aplayer from 'vue-aplayer';
  export default {
    data() {
      return {};
    },
    props: {
      music: {
        type: Object,
        default: () => {
          return {
            title: 'Untitled',
            artist: 'Unknown',
            src: '',
            pic: require('../../assets/images/audio.jpg'),
            lic: 'none',
            theme: 'teal'
          }
        }
      }
    },
    mounted() {
      console.log(this.music);
    },
    beforeDestroy() {
    },
    computed: {},
    methods: {},
    components: {
      Aplayer
    }
  };
</script>
```

**The error message is as follows. The player couldn't play, I found that the `src` and `preload` attribution of tag `audio` were Undefined! **
**Error:** 
![image](https://user-images.githubusercontent.com/22169252/39856138-5eba81ca-5461-11e8-8874-81090f1edd5f.png)
**Warning:**
![image](https://user-images.githubusercontent.com/22169252/39856812-da5e49f4-5463-11e8-8afb-aba0bd4f7583.png)
**DOM:**
![image](https://user-images.githubusercontent.com/22169252/39856965-5e443f62-5464-11e8-83c4-3769f811bc31.png)

**After that, I changed the structure of level3 as follows. The player could play now, but the error info printed in console again!**
```vue
<template>
    <div class="wrap">
        <aplayer :music="{
            title: music.title,
            artist: 'Unknown',
            src: music.src,
            pic: require('../../assets/images/audio.jpg'),
            lic: 'none',
            theme: 'teal'
          }"></aplayer>
    </div>
</template>
```

**That's all, looking forward to your reply.**

**Comment by SevenOutman** [comment]
@Robin-zero Look like this error happens at the `created` stage of `ItemResAudio`, when its `music.src` is an empty string, which will fail Vue-APlayer's `music` prop validator.

To avoid this, always make sure Vue-APlayer's `music` prop has a valid `src`. I'd recommend you not to create a Vue-APlayer instance until you have your music info ready.

**Comment by SevenOutman** [comment]
Closed due to inactivity.
