### ISSUE TITLE
First song doesn't proceed to second on first play

### ISSUE THREAD

**Issue by edencorbin** [SevenOutman/vue-aplayer#40]
This is a silly issue, I'm certain there is a way around this. I have an album as a playlist. I have music set to my first song, and list set to all the songs in the album. The first song will play, then the first song will play from the play list, which is a repeat of the first song. How can I include the first song in the playlist and also play it first, without repeating twice for repeat-all?

**Comment by SevenOutman** [comment]
@edencorbin Could you show me your code please?

**Comment by edencorbin** [comment]
Okay I resolved it. I was filling out all the properties of a music object, when I instead set it as follows everything works as expected. What is the match it makes to determine if the first song is the same is it a deep same comparison? In any case this is resolved as follows, I could see perhaps an update to the documentation? I don't believe there is an actual code example with a list.
```
:music="list[0]"
:list="list"
```

**Comment by SevenOutman** [comment]
@edencorbin Glad you have solved it!. That's exactly what happened.  Vue-APlayer does not compare music objects, but treats them as references, so you should make sure your `music` and the first of your `list` is **the same object**. That means, you cannot use *object literals* as below, which creates two individual objects:
```
:music="{ src: 'a.mp3' }"
:list="[{ src: 'a.mp3' }]"
```
