### ISSUE TITLE
Varying artist length, results in songs not aligning.

### ISSUE THREAD

**Issue by edencorbin** [SevenOutman/vue-aplayer#41]
If you have different length artist names by song (such as featuring xyz), then all the songs go out of alignment, is this intended? I didn't see an api/option to change this.

**Comment by SevenOutman** [comment]
@edencorbin Could you provide some screenshots?

**Comment by edencorbin** [comment]
![alignmentissue](https://user-images.githubusercontent.com/1577795/40155767-537d264e-594a-11e8-9bba-4cdaf73cb8ea.png)

**Comment by edencorbin** [comment]
You can see it is directly offset by the length of the artist name.... I would think some stying options like maybe left align, or perhaps tabled so that centering would still work with two different cells. Most likely I'm missing something that already can be done : ' )

**Comment by SevenOutman** [comment]
@edencorbin It's apparently not intended. And I can't reproduce it.

The screenshot below is taken on https://vue-aplayer.js.org , alignment works as expected. 
![image](https://user-images.githubusercontent.com/8225666/40155983-50f9455e-59c9-11e8-9e06-c4fa25643525.png)

You may check this link to see if it also works all right in your browser.
- If yes, maybe you have some issue in your custom styles.
- If not, please tell me what OS and browsers you're using.

**Comment by edencorbin** [comment]
yes, it looks good on that link.

I'n not applying any custom styling to my knowledge:
```
<template>
  <div>
    <aplayer 
      :music="list[0]"
      :list="list"
      :repeat="'list'"
    />
  </div>
</template>
```
I do have purecss installed, but I just checked ensuring it is not in a purecss element, and that didn't change anything.

**Comment by edencorbin** [comment]
@SevenOutman wrapping it in text-align: left style fixed it..... it would seem artist auto align right, and the song names are whatever your styling is? I guess that is pretty good generally, I'll close out this ticket. I didn't notice much mention of styling in the docs, would be great if that was explained a little.

**Comment by SevenOutman** [comment]
@edencorbin Glad you have solved it! Yes the alignment can be affected by parent elements. This will be fixed in next minor or patch update, in which UI improvements are included.
