### ISSUE TITLE
关于自动播放的问题

### ISSUE THREAD

**Issue by OneKissAndOneShot** [SevenOutman/vue-aplayer#44]
大佬，在使用你的轮子的时候我遇到一个自动播放的问题 
1、点击第一首歌曲可以自动播放 然后再点击其他的歌曲的时候不会自动播放 是不是点击的时候要调用什么方法之类的  
2、我看文档说 假如有多个播放器的话设置自动播放只有第一个会自动播放 但是我这个就一个播放器 搞不明白了 
3、假如要调用play()方法的话 该怎么去调用  
4、我没有用list播放列表 获取到的歌曲信息 存放在一个对象中 点击不同歌曲 改变对象的值

**Comment by SevenOutman** [comment]
@OneKissAndOneShot 首先你说的情况跟”**自动播放**“这个概念没关系…自动播放指的是页面一加载好就开始播放。
根据你的描述我觉得问题可能出在 4 上。如果你要 Vue-APlayer 切换歌曲的话，要把 `music` 对象替换掉，修改 `music` 对象里的 `src` 什么的是不行的。

**Comment by OneKissAndOneShot** [comment]
现在切换歌曲没问题 就是歌曲切换之后还是暂停状态 我想切换之后自动播放 有办法解决么

**Comment by SevenOutman** [comment]
@OneKissAndOneShot 你能展示一下你切换歌曲的代码吗

**Comment by OneKissAndOneShot** [comment]
https://github.com/SevenOutman/vue-aplayer/issues/38  切换歌曲代码就在这个问题里 是不是因为我是直接 对vuex 进行赋值造成的

**Comment by SevenOutman** [comment]
@OneKissAndOneShot 我上面不是说了吗怎么不仔细看，**如果你要 Vue-APlayer 切换歌曲的话，要把 `music` 对象替换掉，修改 music 对象里的 `src` 什么的是不行的**。你的代码就是错误的做法啊。

**Comment by OneKissAndOneShot** [comment]
好的 不改也可以用 我改

**Comment by OneKissAndOneShot** [comment]
大佬教育的是 我改
