### ISSUE TITLE
Silence Version Badge in production

### ISSUE THREAD

**Issue by mateullull** [SevenOutman/vue-aplayer#45]
Hi,

It would be nice if we could silent the ```Version Badge``` on console. Maybe it can be done by a param in the component or detecting the vue environment (development or production). I prefer to silent all console outputs in production (and many libraries do it by default).

https://github.com/SevenOutman/vue-aplayer/blob/e853115553aa39a02dba540d3810d394eff95403/src/vue-aplayer.vue#L70

**Comment by SevenOutman** [comment]
@mateullull Good point. Will be included in next minor or patch update.

**Comment by SevenOutman** [comment]
@mateullull It's done in 6d5fff779f97f98620b7af611543b8bb890b90dd and included in `v1.6.0`

**Comment by mateullull** [comment]
Many thank's @SevenOutman!
