### ISSUE TITLE
New logo design

### ISSUE THREAD

**Issue by nunojesus** [SevenOutman/vue-aplayer#46]
Hi, I need to know if you have something on your mind for your logo? color? shape? 
Do you have any special request?
Can you tell me in what can I get inspired to create the design?

This are a lot of questions :) but I allways want to make a design that the project owner likes it very much.

Greetings 
Nuno Jesus

**Comment by SevenOutman** [comment]
@nunojesus Thanks for your offer.
I don't have a clear image of what I want. Maybe still some element from APlayer and theme from Vue. But I really don't have design sense so don't be limited by my suggestions. At least Vue theme color is a must. This said, it doesn't have to be exactly same colors, but in similar tones is fine.

**Comment by SevenOutman** [comment]
@nunojesus  You may get a clue of what I mean about colors in these Vue-based projects: [Vuetify](https://github.com/vuetifyjs/vuetify), [Element UI](https://github.com/ElemeFE/element), [iView](https://github.com/iview/iview)

**Comment by SevenOutman** [comment]
@nunojesus These are pretty good. Could you add some graphic elements indicating the music-player subject (like a play button or something)? Sorry didn't mention that earlier.

**Comment by SevenOutman** [comment]
@nunojesus I just noticed that there is yet another vue-aplayer and its logo is also designed by you 🤣 , and your offer to it was earlier than my appliance. So I won't force you doing the logo for my project if you get confused about this situation. It's up to you.
Btw I like that logo too 🤣 .

**Comment by nunojesus** [comment]
I will create that for your logo, no problem.

**Comment by nunojesus** [comment]
I create a new design, that have sove variations, see if you like one of this.
In the 3 variations I made also the black versions.

Greetings!

![vue3](https://user-images.githubusercontent.com/34600369/40591062-0c697300-6202-11e8-8406-de0814baa6df.png)

**Comment by SevenOutman** [comment]
@nunojesus Great works! I love the triangles in 2-2 the most. It would be perfect if the gray parts could be ajusted to fit the colored parts better.

**Comment by nunojesus** [comment]
Im happy that you like it, what color do you want?

**Comment by SevenOutman** [comment]
@nunojesus I'm not sure. Maybe a lighter one?

**Comment by nunojesus** [comment]
Here are some color variations of the circle? see if you like one of this, I think que logo works well with out the circle too.

![vue4](https://user-images.githubusercontent.com/34600369/40612889-3c41332a-6274-11e8-978b-774f9a535689.png)

**Comment by nunojesus** [comment]
Hi, Im sorry for the late reply, tomorrow I will make the PR with the logo that you want. Greetings Nuno

**Comment by nunojesus** [comment]
Hello @SevenOutman, I made the pull request with the logo design that you want, and I upload to the README file too, and it looks really good.

If you want my help for your other projects I will be happy to help!

Greetings!

Nuno Jesus

I like this two:
https://github.com/SevenOutman/Hubble
https://github.com/SevenOutman/rsshub.js

**Comment by SevenOutman** [comment]
@nunojesus Thanks for your hard work and interests in my projects!
