### ISSUE TITLE
不能显示播放列表。

### ISSUE THREAD

**Issue by YYQ8023** [SevenOutman/vue-aplayer#5]
首先表示感谢！
我根据文档里的配置好了，其他都没问题，但是**播放列表无法显示**。
后来我用chrome的开发者工具看到了一个“异常”：
dom里：
![image](https://user-images.githubusercontent.com/22813922/27253701-b68ef9ce-53ab-11e7-84e2-d7962894e59b.png)
边上的样式里：
![image](https://user-images.githubusercontent.com/22813922/27253711-fe2310ae-53ab-11e7-8d2f-fedd07963455.png)
``
发现了一个我认为比较“诡异”的css样式“`max-height:88px;height:0px`”，
这可能导致了无法根据歌曲列表来渲染播放列表。

**Comment by YYQ8023** [comment]
在阅读源码 ，似乎是JS设置了这两个样式。

**Comment by YYQ8023** [comment]
通过jq的remoAttr把style给remove就可以了。

**Comment by SevenOutman** [comment]
感谢补充
