### ISSUE TITLE
how to custom theme aplayer?

### ISSUE THREAD

**Issue by VCodepp** [SevenOutman/vue-aplayer#59]
I want to change the existing styles. When I change the background color, it does not work on the others. How can I do it all by myself?

**Comment by SevenOutman** [comment]
@VCodepp Overriding styles on `.aplayer` should work.
```css
.aplayer {
  background: red;
}
```

**Comment by VCodepp** [comment]
yes i know this and it works. I tried it  but I want other controls or ext elements

**Comment by SevenOutman** [comment]
@VCodepp You mean elements inside `.aplayer` right? As the UI design if very important part of Vue-APlayer, it's not and hardly will be mentioned in the docs how to override its styles. I'll show a draft of class hierarchy here but I recommend you use Chrome inspector to find more details.
```yml
.aplayer
  .aplayer-body
    .aplayer-pic
    .aplayer-info
      .aplayer-music
      .aplayer-lrc
      .aplayer-controller
  .aplayer-list
```

**Comment by VCodepp** [comment]
in fact I do not think too much style change. the current design is fine, but it would be nice to be able to change all the colors simply because it does not fit the web in color. It also not working according to the hierarchy.

**Comment by SevenOutman** [comment]
@VCodepp The hierarchy describes only the basic layout of the player. Some color styles are applied on even inner elements. 

For instance, the lyrics text color is applied on `.aplayer-lrc p` selector. So if you write your custom style simply on `.aplayer-lrc`, it won't work, cause the priority of `.aplayer-lrc` selector is lower than `.aplayer-lrc p`. You need to write your custom style for `.aplayer-lrc p`. 

FYI you can use Chrome devtool to inspect on which specific elements or selectors are those styles applied, and then override them.

**Comment by VCodepp** [comment]
I tried what you said, but I did not change it. What's wrong here?

```
span.aplayer-author{
 color: red
}
```

**Comment by SevenOutman** [comment]
@VCodepp Your style rules are overridden by
```css
.aplayer .aplayer-body .aplayer-info .aplayer-music .aplayer-author {
  color: #666;
}
```
because your CSS selector `span.aplayer-author` has lower priority. Try write a ligher-priority selector, or simply add `!important` to your CSS rules.

**Comment by VCodepp** [comment]
This is not working either. I tried every way. Anyway . Thank you for your interest. I guess I should try to use it like this.

**Comment by SevenOutman** [comment]
@VCodepp That's weird. I tried that way and it worked.
I'm closing this issue then. Feel free to reopen if you have further questions.
