### ISSUE TITLE
关于使用 ref 的问题

### ISSUE THREAD

**Issue by OneKissAndOneShot** [SevenOutman/vue-aplayer#63]
我使用 v-if 来控制 aplayer在有数据之后显示  
但是我又遇到一个问题  我想使用ref来获取当前的播放状态
由于ref不是响应式的 所以我获取不到当前的播放状态 
请问有没有什么办法解决

**Comment by SevenOutman** [comment]
@OneKissAndOneShot ref 不是响应式是什么意思…创建 player 之后 ref 仍然是空的？

**Comment by OneKissAndOneShot** [comment]
多谢大佬 可以了

**Comment by OneKissAndOneShot** [comment]
还有一个问题就是 是否支持自定义时间播放
