### ISSUE TITLE
Aplayer controls display ?

### ISSUE THREAD

**Issue by VCodepp** [SevenOutman/vue-aplayer#67]
I use Vue Aplayer. I have a song list on the Aplayer. there is no problem playing and changing songs. but what kind of configuration do I have to make in order to display buttons like stop and pause in the widget template. I could not find any documentation either.

**Comment by SevenOutman** [comment]
@VCodepp What do you refer to as 'the widget template'? The play/pause toggle button is on the album cover.

**Comment by VCodepp** [comment]
I see play and pause button. But I want display next prev button.

**Comment by SevenOutman** [comment]
@VCodepp There's no prev/next buttons in Vue-APlayer v1, you can switch between songs using the playlist. If you want to add elements to Vue-APlayer's ui, use `display` slot.
