### ISSUE TITLE
autoplay not working

### ISSUE THREAD

**Issue by emotality** [SevenOutman/vue-aplayer#69]
Hi, thanks for lib! Awesome, except autoplay doesn't work for me, I tried:

```
autoplay
autoplay=true
autoplay="true"
:autoplay
:autoplay=true
:autoplay="true"
```

Please help 😒 

```vue
<template>
    <div class="row musicplayer">
        <div class="col-md-6 offset-md-3 col-sm-12 offset-sm-0">
            <aplayer autoplay :music="song"></aplayer>
        </div>
    </div>
</template>

<script>
    import Aplayer from 'vue-aplayer';
    export default {
        components: {
            Aplayer
        },
        props: ["title", "artist", "src", "img"],
        data () {
            return {
                song: {
                    'title': this.title,
                    'artist': this.artist,
                    'src': this.src,
                    'pic': this.img,
                    'theme': 'pic'
                },
            };

        }
    }
</script>
```

**Comment by SevenOutman** [comment]
@emotality Try `:music="song"`. You don't use `this` in templates.

**Comment by emotality** [comment]
Thanks @SevenOutman I edited my question, but still no luck. Anything else I'm doing wrong? 😒

**Comment by SevenOutman** [comment]
@emotality I see you are passing `src` from props, maybe it's not a valid value at the time your component is created, e.g. an empty value. Make sure that `src` is valid when `aplayer` is created.

**Comment by emotality** [comment]
Its hardcoded in my PHP (using Laravel) for now till I want to make it dynamic.

```
<music-player title="Song Name" artist="Artist Name" src="{{ asset('/music/1.mp3') }}" img="{{ asset('/music/1.jpg') }}"></music-player>
```

This is instant 🤔 no?
Sorry about the back and forth 🙈

**Comment by thenightex** [comment]
Are you using Chrome to test it by any chance? They've completely deactivated autplay and you have to manually focus the the control or something first. [Source iirc](https://bugs.chromium.org/p/chromium/issues/detail?id=840866#c103)

**Comment by SevenOutman** [comment]
@thenightex I've heard of this change on iOS Safari. But autoplay on https://vue-aplayer.js.org still works totally ok with my Chrome 67.

**Comment by thenightex** [comment]
Yea I'm not totally sure about it but autoplay doesnt work on the chrome Ive got on my working pc. I will check the version tomorrow. It was just the first thing that came to my mind.

**Comment by emotality** [comment]
@thenightex @SevenOutman  Thank you!! It was only a setting in my Safari. 🙏 

Safari Preference -> Websites -> Allow All Auto-Play

Thanks guys, working great now! 😊
