### ISSUE TITLE
切换歌曲时报错

### ISSUE THREAD

**Issue by LancelotLewis** [SevenOutman/vue-aplayer#7]
组件初始化使用Obejct，Object重新赋值时，控制台报错
![image](https://user-images.githubusercontent.com/8749615/28820616-e458b7bc-76e4-11e7-90aa-36ee4e98e5af.png)

**Comment by SevenOutman** [comment]
@LancelotLewis 请提供能充分重现这个问题的代码

**Comment by LancelotLewis** [comment]
@SevenOutman 问题我在刚刚已经解决，你在组件的watch钩子中，直接将music的改动值赋值给aplyer的`option.music` 参数，其实是有问题的，`option.music`是一个数组，所以这里还需要加上一个判断是否为数组，并且转换成数组的代码。
```
watch: {
            music(music) {
                this.control.option.music = music;
                this.control.setMusic(0);
                if(this.autoplay) {
                    this.control.play();
                }
                this.$emit('change', music);
            }
        },
```
完成这一步之后，重置music值时仍然无法切换当前正在播放的歌曲，具体原因不知，但是我发现，手动去设置页面中`audio`标签的`src`值即可完成切歌功能：
```
this.$refs.aplayer.control.audio.src = url;
```
建议你把这句代码放到`watch`中`setMusic`之前，应该是没有问题，仅为个人意见，不喜勿喷，谢谢。

**Comment by SevenOutman** [comment]
@LancelotLewis 目前 vue-aplayer 是不支持监听 music 数组的，这在其他的 issue 中已经讨论过。原因是其依赖的 [APlayer](https://github.com/MoePlayer/APlayer) 并没有提供修改 musicList 的 API。如果你有好的思路能在这种情况下实现监听 music 数组的功能，欢迎提 PR。
