### ISSUE TITLE
How to use play pause event ?

### ISSUE THREAD

**Issue by VCodepp** [SevenOutman/vue-aplayer#71]
I need other button click after play or pause event ?

**Comment by SevenOutman** [comment]
@VCodepp 
This should work.
```vue
<aplayer @play="onPlay" @pause="onPause" />
```

**Comment by VCodepp** [comment]
Actually, what I want to do is a dynamic playlist. That is, the 3 buttons change the aplayer separately

I dont understand @play="onPlay" (onPlay ? event or ? ). Please write very basic example code :/

**Comment by SevenOutman** [comment]
@VCodepp Um did you read Vue’s docs on [error handling](https://vuejs.org/v2/guide/events.html)? It’s just basic usage. `<aplayer>` emits an event named `play` and `onPlay` is a `method` on your component, and `@play="onPlay"` is how you create the binding that your `onPlay` will be invoked when `play` event is emitted.

```vue
<aplayer @play="onPlay" />

// your parent component
methods: {
  onPlay () {
    console.log('Vue-APlayer emitted play event!')
  }
}
```

**Comment by SevenOutman** [comment]
@VCodepp I see. What you want is "let the player play/pause", not "let me know if the player plays/pauses", right? So what you need is probably `play()` and `pause()` API, not `play` and `pause` event.

First off, if you want to change the music, you should **change the `music` object** instead of **changing its `src` property**. 
Then if you want to *let the player start to play*, you can use `thenPlay()` method on the player instance, like

```vue
<aplayer :music="dynamic" ref="player" />

changeMusic(n) {
  this.dynamic = { src: this.music[n] }
  this.$refs.player.thenPlay()
}
```

**Comment by VCodepp** [comment]
@SevenOutman  Awesome!. Thank you. With this code, the other aplayer stops automatically.

**Comment by zhangming8691** [comment]
> @VCodepp I see. What you want is "let the player play/pause", not "let me know if the player plays/pauses", right? Then what you need is probably `play()` and `pause()` API, not `play` and `pause` event.
> 
> First off, if you want to change the music, you should **change the `music` object** instead of **changing its `src` property**.
> Then if you want to _let the player start to play_, you can use `thenPlay()` method on the player instance, like
> 
> ```
> <aplayer :music="dynamic" ref="player" />
> 
> changeMusic(n) {
>   this.dynamic = { src: this.music[n] }
>   this.$refs.player.thenPlay()
> }
> ```

Thanks, the answer helped me.
