### ISSUE TITLE
How to access currentMusic inside slot="display"?

### ISSUE THREAD

**Issue by 8ctopotamus** [SevenOutman/vue-aplayer#72]
Hey, awesome component! I am going to be using this in a podcast player widget.

In the docs you say "The component in this slot will receive two props: `currentMusic` and `playStat`", but I am having trouble accessing the `currentMusic` prop within this slot. 

```vue
<aplayer
    autoplay
    :music="currentPodcast"
    :list="podcasts"
    :shuffle="false"
  >
    <span slot="display">
        // I want to access currentMusic to display a description of the podcast.
        // Accessing {{currentMusic.whatever}} doesn't work.
    </span>
</aplayer>
```

Any tips or examples of showing how to do this would be great! Thanks.

**Comment by SevenOutman** [comment]
@8ctopotamus Thanks for using Vue-APlayer!

You should use *scoped slots* to access the props that a component passes to its slots.
This should work
```vue
<aplayer>
  <template slot="display" slot-scope="{ currentMusic, playStat }">
    <span>{{ currentMusic.whatever }}✓</span>
  </template>
</aplayer>
```

Detailed explanation in Vue docs here: https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots

**Comment by 8ctopotamus** [comment]
Perfect, thanks!
