### ISSUE TITLE
how can i select with a click event on the outside of the song aplayer

### ISSUE THREAD

**Issue by VCodepp** [SevenOutman/vue-aplayer#73]
I have a list in aPlayer. I display the list on aPlayer in a different area. I want the 'xw' to start the same song when the user clicks on any list in track  this area.

**Comment by SevenOutman** [comment]
@VCodepp I think it's actually the same question with https://github.com/SevenOutman/vue-aplayer/issues/71

**Comment by VCodepp** [comment]
Actually, you're right.
