### ISSUE TITLE
watching of the finished music ?

### ISSUE THREAD

**Issue by VCodepp** [SevenOutman/vue-aplayer#74]
I need to watching finished 'aplayer' music. Because my element class 'pause' change 'play'

**Comment by SevenOutman** [comment]
@VCodepp [As explained in the docs](https://github.com/SevenOutman/vue-aplayer/blob/develop/docs/README.md#events), Vue-APlayer emits [a full list](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events) of MediaEvents, so you can listen to `ended` event.

Or if what you want is simply knowing whether the player is playing or not, you can use `this.$refs.player.isPlaying` property.

**Comment by SevenOutman** [comment]
@VCodepp FYI our [Discord server](https://discordapp.com/invite/e3SeMJE) is a good place to ask usage questions.

**Comment by VCodepp** [comment]
I need music end watching. How to watching ?

watch:{
   '$refs.demoPlayer.ended':(){
       this.ending=this.$refs.demoPlayer.ended;
   }
}

**Comment by SevenOutman** [comment]
@VCodepp You should probably get clear about what events are and how to use them in Vue docs on [event handling](https://vuejs.org/v2/guide/events.html).

**Comment by VCodepp** [comment]
Yeah. I finally got it. If you shared the codes directly, I would not have understood it. Thank you for your interest.
I solve the problem like this ; 

```
<aplayer 
    v-if="music" 
    ref="demoPlayer" 
   controls 
   :music="music[current]" 
   style="display:none"  
   + @ended="ifEnd= $event"
/>
```
```
watch: {
      ifEnd() {
       console.log('end')
      }
    },
```

**Comment by SevenOutman** [comment]
@VCodepp Glad you learned new things!

Here's how your solution can look better
```vue
<aplayer @ended="onMusicEnded" />

methods: {
  onMusicEnded() {
    console.log('end')
  }
}
```

**Comment by SevenOutman** [comment]
@king-Senior 这个 issue 可能会帮到你。另外提问请提在正确的地方。
