### ISSUE TITLE
Listening To Media Events

### ISSUE THREAD

**Issue by Shadomax** [SevenOutman/vue-aplayer#75]
Please how can i listen to the events listed [here](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events) specially the progress and duration change

**Comment by SevenOutman** [comment]
@Shadomax You'll probably find https://github.com/SevenOutman/vue-aplayer/issues/74 helpful.

**Comment by Shadomax** [comment]
yeah thank you, i already fixed it. 
But am having trouble loading new song to play when i load new content to the music prop.
Can you help with these?

**Comment by SevenOutman** [comment]
@Shadomax Could you show me some code you doing 'load new content to the music prop'? You can either comment below, or move to our [Discord group](https://discordapp.com/invite/e3SeMJE).
