### ISSUE TITLE
Click on the progress bar will pause once

### ISSUE THREAD

**Issue by Ice-Hazymoon** [SevenOutman/vue-aplayer#78]
Pictured: 

![mmmmm.gif](https://i.loli.net/2018/06/26/5b31dda47d9cd.gif)

[Aplayer](https://github.com/DIYgod/APlayer) does not have this problem

**Comment by SevenOutman** [comment]
@Ice-Hazymoon This is intended because it's how native `<audio>` element behaves.

**Comment by Ice-Hazymoon** [comment]
How can I solve it

**Comment by SevenOutman** [comment]
@Ice-Hazymoon If you still find this UI behavior confusing, there will be an enhancement for this included in upcoming `Vue-APlayer@2`. Make sure to keep an eye on it.

**Comment by Ice-Hazymoon** [comment]
Ok, thanks!
