### ISSUE TITLE
H5的样式很难控制

### ISSUE THREAD

**Issue by a3246995** [SevenOutman/vue-aplayer#79]
功能蛮不错的,就是H5的话样式估计很难控制...

**Comment by SevenOutman** [comment]
@a3246995 请问有遇到实际问题吗？有的话请清楚地描述你的问题，没有的话我将关闭这个 issue。

**Comment by a3246995** [comment]
麻烦了 有,譬如各个手机尺寸样式全乱了,我想直接操作样式很难控制...

**Comment by a3246995** [comment]
具体些,譬如iphone5

**Comment by SevenOutman** [comment]
@a3246995 请你**清楚地**描述你的问题，至少要让我明白你遇到的问题是什么样的。比如展示你的代码或者一些截图，并描述预期的结果和实际的结果哪里不符。

**Comment by a3246995** [comment]
譬如手机尺寸iPhoner5,基本宽度320左右的就挂了样式...

**Comment by a3246995** [comment]
![wechatimg872](https://user-images.githubusercontent.com/24914203/42008712-8c27ba1e-7ab9-11e8-980b-721752210ae7.jpeg)

这是截图

**Comment by a3246995** [comment]
基本宽给100%刚好,但我样式给少点就乱了基本在320px宽的尺寸左右,例如iphone5这些,我给了80%就乱了

**Comment by SevenOutman** [comment]
@a3246995 那你弄宽点不就行了…控制区域的确有那么多按钮要放，太窄了就会挤在一起呀。

或者如果你对于窄屏幕下隐藏某些按钮有好的建议，也欢迎提出来。

**Comment by a3246995** [comment]
....我试下吧你的样式有些难控制,还好我用了sass:
.box{
    width: 100%;
    margin-top: 30%;
    display: flex;
    justify-content: center;
    // border: 1px solid black;
    // align-items: center;
    // flex-flow: row wrap;
    // align-content: space-between;
    .music{  //音乐控件
      width: 90%;
      background: linear-gradient(to top, #fddb92 0%, #d1fdff 100%);
      :before{
        opacity: 0;
      }
      :after{
        opacity: 0;
      }
    }     
  }

**Comment by a3246995** [comment]
嗯....你说的对
