### ISSUE TITLE
with vue2. exception

### ISSUE THREAD

**Issue by lj-211** [SevenOutman/vue-aplayer#83]
### after building with vue2，an exception happened. 
`
vue-aplayer:1 Uncaught TypeError: Cannot read property 'version' of undefined
    at Object.<anonymous> (vue-aplayer:1)
    at e (vue-aplayer:1)
    at Object.<anonymous> (vue-aplayer:1)
    at e (vue-aplayer:1)
    at vue-aplayer:1
    at vue-aplayer:1
    at vue-aplayer:1
    at vue-aplayer:1
`

env:
   vue version: 2.5.2

**Comment by SevenOutman** [comment]
@lj-211 Make sure Vue is included correctly in your bundle.
