### ISSUE TITLE
关于通过其他按钮主动触发播放的相关建议

### ISSUE THREAD

**Issue by gjycdd** [SevenOutman/vue-aplayer#87]
1. 为什么会有这样的需求？
在我当前的项目中，我需要以一个图层先盖住Aplayer,
然后通过点击图层上的按钮，去触发播放器的播放。
就像是这样

 =============
 | -------------------- | 
          ----------
 | ----  |    run    | ---- |
          ----------
 | -------------------- |
> =============

2. 我当前的操作
```
<div ref="mediaAudio" class="mediaAudio position-center" v-show="type === 'audio' && isStart">
        <aplayer
          preload="preload"
          :music="{
            title: 'secret base~君がくれたもの~',
            artist: 'Silent Siren',
            src: 'https://moeplayer.b0.upaiyun.com/aplayer/secretbase.mp3',
            pic: 'https://moeplayer.b0.upaiyun.com/aplayer/secretbase.jpg',
          }"
        />
 </div>
<div @click="startMedia"></div>
```
为什么要多个容器呢，因为我直接在aplayer上用ref会报错
```
startMedia() {
      if (!this.src) {
        this.$toast('媒体获取失败');
        return;
      }
      this.isStart = true;
      if (this.type === 'video') {
        this.vPlay(); // 视频播放，此处忽略
      } else {
        this.aPlay(); // 音频播放，请关注
      }
},
aPlay() {
      const audioWrap = this.$refs.mediaAudio; // 取到容器
      this.aPlayer = audioWrap.querySelector('audio'); // 容器下查找到radio
      this.$nextTick(() => {
        this.aPlayer.play(); // play
      });
},
```
一开始我没有用nextTick去手动异步，然后我发现，wow，play不了，然后我写了个块，明白了。
以上我才实现了手动触发播放。挺麻烦的吧？

3. 我希望的
是不是可以支持在aplayer上添加ref
然后通过ref在取到的vdom上的某个方法直接触发播放呢？
类似于[DPlayer](https://github.com/MoePlayer/vue-dplayer)的`this.$refs.player.dp.play()`方法。

综上

**Comment by SevenOutman** [comment]
@gjycdd https://github.com/SevenOutman/vue-aplayer/issues/71

**Comment by gjycdd** [comment]
嗯， 看了下71，thenPlay可以，我觉得最好在文档上写一下吧，说实话我撸了好几遍文档都还是懵的
emmmmmm

**Comment by SevenOutman** [comment]
@gjycdd 没有写在文档里是因为这本不是 Vue-APlayer 预期提供的功能，只是可以这样用而已。

使用 Vue-APlayer 的时候遇到问题可以先在 issues 里搜索下是否已有解答，或者加入我们的 Discord 频道来提问。
