### ISSUE TITLE
能否做到introloop？

### ISSUE THREAD

**Issue by lshy1993** [SevenOutman/vue-aplayer#89]
感谢这个插件，想问一下，我的wav是类似 I-L-E 的这种，想要做到Loop部分w无限循环有可能吗？
就是从a时间点开始到b时间点无缝循环之类的

**Comment by SevenOutman** [comment]
@lshy1993 可以实现，但是并不打算去做。
1. 常见的播放器没有提供这个功能
2. 如果用 props 来控制 AB 点的话很容易不精确，导致听起来会有断层，效果并不好
3. 进度条无论是停在原地不动，还是反复跳回之前的时间点，对于用户来说都是会引起困惑的

**Comment by lshy1993** [comment]
感谢看来只能用web audio api来实现了，另一个遇到的问题是，设置了autoplay，第一次进入网页能够自动播放，router更新后，（将music的src重新计算后）播放器就停止了，不会再次自动播放，有什么解决方案吗？

**Comment by SevenOutman** [comment]
@lshy1993 切换歌曲应该直接替换 `:music` 对象，而不是只修改里面 `src` 的值。
