### ISSUE TITLE
关于事件触发播放/暂停的机制如何实现

### ISSUE THREAD

**Issue by xiezhengsu** [SevenOutman/vue-aplayer#9]
请问一下，vue-aplayer在使用中，如果通过一个函数调用它的播放/暂停事件，这个需要怎么使用，演示的demo中是有这样的功能实现的，只是在源码中没有找到对应的方法？？

**Comment by SayGoodBey** [comment]
同上  事件调用

**Comment by SevenOutman** [comment]
不再活跃的话题
