### ISSUE TITLE
使用插件时遇到的问题

### ISSUE THREAD

**Issue by subdance** [SevenOutman/vue-aplayer#91]
Cannot read property 'version' of undefined
请问这个该怎么解决
ps我也蛮喜欢摇曳百合的

**Comment by SevenOutman** [comment]
@subdance 看起来和 #83 是同样的问题，你可以参考下

**Comment by subdance** [comment]
@SevenOutman 谢谢赛文奥特曼

**Comment by subdance** [comment]
我执行了如下代码
`npm install -g @vue/cli`
`vue init webpack vue-demo`
`cd vue-demo`
`npm install ajv@^6.0.0`
`npm i vue-aplayer`
`npm install --save hls.js`
`npm run dev`
![3](https://user-images.githubusercontent.com/26321549/42998306-54d3ccb6-8c4c-11e8-8835-5778bb3ab205.PNG)
还是这样
