### ISSUE TITLE
Validation warning

### ISSUE THREAD

**Issue by atilkan** [SevenOutman/vue-aplayer#99]
I get custom validation error even though i fill every bit of option.

![screen shot 2018-08-15 at 11 33 01](https://user-images.githubusercontent.com/1254613/44139265-3c88afb8-a07f-11e8-8f2f-208e61ca2f58.png)

<img width="306" alt="screen shot 2018-08-15 at 11 33 38" src="https://user-images.githubusercontent.com/1254613/44139279-4838b7cc-a07f-11e8-9673-9d1060c97073.png">

**Comment by Sweetjqq** [comment]
我也遇见这个问题了，在music的src属性里面给一个默认的地址，或者以.mp3结束的字符串就不会报错了

**Comment by atilkan** [comment]
@Sweetjqq What do you mean?
